### ISSUE TITLE
Why modules are in installable=False state ?

### ISSUE THREAD

**Issue by ingfred** [OCA/management-system#103]
Hello.
I would like to test some these modules.
But i can't install anything.
Should I change installable=False into True to make this possible.
If I do that, is there any consequences  ?
Thx

**Comment by pedrobaeza** [comment]
Because they are still not migrated to v9. You can track the progress here: https://github.com/OCA/management-system/issues/92

**Comment by ingfred** [comment]
Thank you for this answer.
Can I change installable=False into True if i want to test with the v8 for test.

**Comment by ingfred** [comment]
Sorry.
I didn't git clone the good version.
Thx for all.
