### ISSUE TITLE
Missing 'knowledge' dependencies

### ISSUE THREAD

**Issue by gborelli** [OCA/management-system#12]
Some modules depend on document_page_approval.
It seems this dependency is not ported to Odoo v8 - https://github.com/OCA/knowledge

Did somebaody start the porting of knowledge packages?
Please, let me know how I can help

**Comment by pedrobaeza** [comment]
There isn't any module yet ported to v8, so if you want, you can help with the migration task. It would be much appreciated.

Regards.

**Comment by gborelli** [comment]
ok, thank you

I have started to port the necessary modules from 'knowledge' bundle, here - https://github.com/abstract-open-solutions/knowledge/tree/8.0-gborelli

**Comment by pedrobaeza** [comment]
Please make a PR for each module here.

**Comment by dreispt** [comment]
Pedro surely means to suggest making those PRs into the corresponding project https://github.com/OCA/knowledge .

**Comment by pedrobaeza** [comment]
Sorry, I see wrong the project. Yeah, I mean there.

Thanks Daniel for the precission.

**Comment by llacroix** [comment]
:+1:

**Comment by dreispt** [comment]
Fixed by #21.
