### ISSUE TITLE
[ERROR] A traceback is being shown when go to manuals and procedures in runbot.

### ISSUE THREAD

**Issue by nhomar** [OCA/management-system#120]
Hello.

Just open Runbot and go to menus on the image.

![](https://www.evernote.com/l/AJ6hVdi-jPtDHJkIp_ze4A-wMdAvmHy3OjYB/image.png)

**Comment by nhomar** [comment]
It is happening in hazards also.

![](https://www.evernote.com/l/AJ7Zs2aC7-VOobG9gBvMrAKjnTa9-56ncJgB/image.png)

**Comment by max3903** [comment]
@nhomar I am assuming you used version 8.

I didn't get the error message when accessing the procedures.

Regarding the hazards, you need to set the default formulae on the company to compute the risk. I would like to set a default value, but the data is loaded later so I changed to have the field required in the view (and not in the model) but I haven't found time to ask for the default value during the installation.
