### ISSUE TITLE
ISO 13485:2016 - Medical devices

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#126]
2016 version:
http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=59752

Previous version (2003):
http://www.iso.org/iso/catalogue_detail?csnumber=36786

**Comment by max3903** [comment]
@OCA/vertical-medical-maintainers Just for your information.

**Comment by dreispt** [comment]
Pinging the top contributors there: @lasley @echeverrifm @JonathanNEMRY @parthivgls @TheCloneMaster

**Comment by TheCloneMaster** [comment]
Hi, did you notice it's status...
It says : *95.99, *
that means:
Withdrawal of International Standard

Regards,
Mario

**Comment by lasley** [comment]
Any reason we aren't going for the newer ISO 13485:2016 instead?

**Comment by max3903** [comment]
@lasley It wasn't available when I created the issue. I updated the link in the description.

**Comment by lasley** [comment]
Awesome! My team would love to assist in this project - we'll begin getting familiar with the standard :+1:
