### ISSUE TITLE
Migrate mgmtsystem_information_security to version 8

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#127]
Migrate mgmtsystem_information_security and its dependencies to version 8
- [ ] mgmtsystem_severity
- [ ] mgmtsystem_probability
- [ ] mgmtsystem_security_event
- [ ] mgmtsystem_information_security

**Comment by wagnerpereirasp** [comment]
Hello max3903, I also want to participate on this migration.

**Comment by max3903** [comment]
@wagnerpereirasp To version 8? I think @naousse is working on it on version 9. See #92
