### ISSUE TITLE
Fail in mgmtsystem_claim

### ISSUE THREAD

**Issue by igallart** [OCA/management-system#135]
Hello, there is a error in Javascript with a action:

https://github.com/OCA/management-system/blob/8.0/mgmtsystem_claim/views/board_mgmtsystem_claim.xml

In a fresh installation (with data demo or no data demo), when is installed the module mgmtsystem_claim, after in Reporting>Management Systems show a error:

Odoo Client Error
Uncaught Error: % undefined as prefix
http://127.0.0.1:8069/web/js/web.assets_backend/740aec7:2655

The error is related with the domain, if it is removed, it works.

```
 <record model="ir.actions.act_window" id="action_mgmtsystem_claim">
      <field name="name">board.mgmtsystem.claim.act_window</field>
      <field name="res_model">mgmtsystem.claim</field>
      <field name="view_type">form</field>
      <field name="view_mode">tree</field>
      <field name="domain">[('stage_id.id', 'in', (%(stage_draft)d, %(stage_open)d, %(stage_pending)d))]</field>
    </record> 
```

**Comment by dreispt** [comment]
Checked on Runbot,v8.0, and I confirm it.
The `%()` is supposed translate an XMLId into a database ID.
Probably the names used are not correct XML IDs.

**Comment by dreispt** [comment]
@llacroix Do you have time to check?

**Comment by llacroix** [comment]
Not much time, but the error is strange honestly. @dreispt if the xmlid was wrong, it should raise an error that the xmlid cannot be found or something like that. It shouldn't even get to the client. It seems more like the xmlid replacement is not happening at all. 

I'd try to put that code into an `eval="[('stage.id', 'in', [ref('stage_draft')...])]"`

Chances are that it will work better that way than the string replacement

**Comment by dreispt** [comment]
@igallart Can you try a fix?

**Comment by igallart** [comment]
OK, I try the solution of @llacroix and it works:

> ```
>   <record model="ir.actions.act_window" id="action_mgmtsystem_claim">
>       <field name="name">board.mgmtsystem.claim.act_window</field>
>       <field name="res_model">mgmtsystem.claim</field>
>       <field name="view_type">form</field>
>       <field name="view_mode">tree</field>
>       <field name="domain"
>           eval="[('stage_id.id', 'in', [ref('stage_draft'), ref('stage_open'), ref('stage_pending')])]" />
>   </record>
> ```

**Comment by dreispt** [comment]
Can you submit a PR?

**Comment by igallart** [comment]
Yes.
https://github.com/OCA/management-system/pull/136

**Comment by dreispt** [comment]
Great! :tada:
