### ISSUE TITLE
No documentation for installation

### ISSUE THREAD

**Issue by omerfarooX** [OCA/management-system#139]
Hello Everyone. 
I have an odoo 9 enterprise edition and i would like to install all these modules or atleast the document_page_quality_manual module. I tried uploading it to the addons folder and then also updated the modules list but i still dont see it anywhere. Any help regarding this issue would be great :)

**Comment by max3903** [comment]
@omer414 Do you have any filter on the module list? Have you tried the same process with another module? Does it work?

You can also use the module from Apps:
https://www.odoo.com/apps/modules/9.0/document_page_quality_manual/

or Wheelhouse:
http://wheelhouse.odoo-community.org/

**Comment by omerfarooX** [comment]
Thanks @max3903 for your response. Actually i am searching these modules under apps. Because i think this is where all apps and modules are kept in v9 (and i have tried without any filters). I did try adding enterprise addons with the same method but they were in separate directories, but they did work. Thanks for the wheelhouse link, will definitely check it out. 

So let me explain the process i followed to install the modules ( There might be something i am doing wrong): 
1. I downloaded the zip directly into addons (from the address 
   https://apps.odoo.com/loempia/download/document_page_quality_manual/9.0.1.0.0/5rLL34bQMqDBXlFQMr3dXJ.zip?deps)
   Got this link from here https://www.odoo.com/apps/modules/9.0/document_page_quality_manual/.
2. Next i unzipped this file inside the addons directory, so i got 6 new folders inside the addons directory.
   1) document_page 2) document_page_approval 3) document_page_quality_manual 4) knowledge 5)  mgmtsystem 6) mgmtsystem_manual
3. Then i enabled development mode/ technical features and clicked on "update modules list".

Is this correct?

**Comment by max3903** [comment]
I think you need to restart Odoo.

**Comment by omerfarooX** [comment]
Thanks max, found it :)

**Comment by max3903** [comment]
@omer414 Great! Can you close the issue please?

**Comment by omerfarooX** [comment]
Sure, thanks
