### ISSUE TITLE
8.0 branch doesn't work with odoo 8.0

### ISSUE THREAD

**Issue by gborelli** [OCA/management-system#15]
I tried to use modules in 8.0 branch with Odoo v8.0 but it seems these modules don't work.

There are many wrong imports
- https://github.com/OCA/management-system/blob/8.0/mgmtsystem/mgmtsystem_system.py#L22 
- https://github.com/OCA/management-system/blob/8.0/mgmtsystem_action/mgmtsystem_action.py#L22

There also are some reference to non-existent models, such as survey.type:
- https://github.com/OCA/management-system/blob/8.0/mgmtsystem_survey/mgmtsystem_survey.xml#L13

This branch also lacks of a valid .gitignore file.

Maybe did somebody miss to move all packages to **unported** directory?

**Comment by dreispt** [comment]
The project is not yet migrated to 8.0.
Right now there shouldn't be any modules available to install in the 8.0 branch.

**Comment by max3903** [comment]
FYI
https://github.com/OpusVL/odoo-mgmtsystem
https://github.com/OpusVL/odoo-mgmtsystem/issues/17

**Comment by dreispt** [comment]
Unfortunately that looks stale; I wouldn't wait on it.
And the proper way would be doing a steady stream of ported modules, proposed one by one.

**Comment by dreispt** [comment]
Solved by #14
