### ISSUE TITLE
[9.0] Move and rename mgmtsystem_kpi

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#154]
# kpi
- [x] Move mgmtsystem_kpi in https://github.com/OCA/server-tools
- [x] Rename it `kpi`
- [x] Add a menu item here:
- Dashboards 
  - Dashboards
    - Dashboards
    - KPI
# mgmtsystem_kpi

See #92

**Comment by max3903** [comment]
ping @OCA/tools-maintainers

**Comment by dreispt** [comment]
:+1:

**Comment by max3903** [comment]
@dreispt Any suggestion for the place of the menu item? I am thinking under the Dashboard app.

I think we should also keep mgmtsystem_kpi to add a menu item under Management System > Reports.

**Comment by dreispt** [comment]
Dashboard sounds good. Yes, mgmtsystem_kpi can be kept as a minimal module, with a dependency on kpi and that extra menu. It's also good to have visibility on the kpi feature inside the mgmtsystem repo.

**Comment by max3903** [comment]
@naousse I just updated the #92 to add the menu item `KPI` under `Reports`.

For the module `kpi`, we need to add a menu item here:
- Dashboards 
  - Dashboards
    - Dashboards
    - KPI

Thanks!

**Comment by max3903** [comment]
@naousse Please review https://github.com/naousse/management-system/pull/14
