### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by levkar** [OCA/management-system#162]
ISO 9011:2015 introduces process approach. 
http://www.iso.org/iso/iso9001_2015_process_approach.pdf

CMMI is also process based. 
https://en.wikipedia.org/wiki/Process_area_(CMMI)

And following page advises a lean approach with processes and treat work instructions as procedure (as far as I understand)
http://www.pinnacleeg.com/iso/iso-9001-myth-5-process-vs-procedure/

Following page describes process procedure and work instruction clearly:
http://the9000store.com/iso-9000-tips-process-procedure-work-instruction/

Procedures or manual can be used to fulfill processes but we can also introduce the process concept.

document_page_process
mgmt_system_process

Let me know what you think and I can develop and send.

@max3903

**Comment by max3903** [comment]
Hello @levkar 

Manuals, procedures (including processes), environmental aspects, hazards and security events are documented through document pages because it is easier to relate other objects (like nonconformity or verification line) to the same object.

What would be the fields of the process object you propose? How would you relate it with the others?

**Comment by dreispt** [comment]
AFAICT Processes are currently supported (it couldn't ba differently since they are key to ISO9001).
Before any development is started, can you detail the design and features you would like to implement?

**Comment by levkar** [comment]
@max3903 : manuals are kept more compact with references to processes which are another kind of document page.  it is kind of sub-chapter of a manual. why i propose an entity named process, is that it is a  distinctive term in quality standarts. A process is something between manual and procedure. You can get more information from the links i provided.

@dreispt : processes are introduced in ISO 9001:2015. how do we handle them with management system? do we use manuals for processes?

We are currently focused on CMMI because it is more specific to our business. CMMI is a process based approach and clearly tells you to define and improve processes. There are also goals and practices which can be specific to process or generic. They can be handled as procedures while processes can be handled as manuals.

**Comment by dreispt** [comment]
In the current design, we can reference "Procedures", that are expected to be `document.page` records.
In theory, a "Process" can have many "Procedures", and these in turn may have "Work Instructions".
All these are part of the "Quality Manual", so I can see that all these correspond to `document.page` records.

@max3903 Maybe we should have a "Type" field in `document.page` to identify the typo of document,a nd be able to know what are Procedures and what are Processes?

@levkar Again, what would be your requirements to represent Processes in the Management System?

**Comment by levkar** [comment]
Your conclusion is correct. Process is just another page like manuals and procedures. Only requirement is to have a "Process" menu like "Procedures" menu.

**Comment by max3903** [comment]
@levkar What do you think of a cmmi module providing the process category (as a document page category) and all the processes of the CMMI (as document pages)?

**Comment by dreispt** [comment]
I can see that Document Pages already have a `type` selection field, with options "Content" and "Category". 
I'm not sure what they are supposed to mean, and not sure if Management System should extend that list, or add a category field.
But this addition is generic to Management Systems, and not specific to CMMI.

**Comment by max3903** [comment]
:+1:
