### ISSUE TITLE
Ported this to v10 and got workflows back from v8

### ISSUE THREAD

**Issue by eugen-don** [OCA/management-system#163]
Hi guys i have ported the following apps to v10:
mgmtsystem, mgmtsystem_action, mgmtsystem_audit, mgmtsystem_hazard, mgmtsystem_nonconformity, mgmtsystem_review, mgmtsystem_survey.

My client had the following requirement:
The effectiveness review in the module mgmtsystem_nonconformity, needed to be packed into its own stage. And we decided to put the effectiveness review behind the progress stage, since it doesnt make sense to evaluate the effectiveness of a task, an action or a process which hasnt been finished yet.
In addition i was asked to migrate the workflows of approving the analysis and actionplan to version 10.0 which seem to have been discarded in the migration from 8.0 to 9.0.

Id like to know if there was any reason for discarding the concept of planning, or lets say entering data by person A, and getting it approved by person B (e.g. the Manager/ Superior). If there was actually a reason for discarding the workflows i could put them into a separate module.

Also i would like to know if it is acceptable to have the effectiveness review as a separate stage behind the progress stage? If this was acceptable i could drop my developement on the custom module for an additional stage and just modify the mgmtsystem_nonconformity to support the additional Stage in the workflow.

**Comment by max3903** [comment]
Thanks @eugen-don.

:+1: for the new stage

Can you please comment on the issue #159 and let us know the modules you migrated and their pull requests?

**Comment by eugen-don** [comment]
@max3903 
Sorry for the wait, i got ill and wasnt able to work for a while...
heres the pull 1:
https://github.com/OCA/management-system/pull/165

pull 2 with rest of repo will ready in few days.
