### ISSUE TITLE
[8.0] Doesn't display procedure list when creating audit > verification list.

### ISSUE THREAD

**Issue by aferreroc** [OCA/management-system#185]
When I'm creating audit, and filling verification list with questions and when I try to associate to a procedure, the list aren't displayed.
And when I create the procedure directly inside vertification list, the previously created procedures aren't displayed.

management-system branch 8.0

**Comment by eugen-don** [comment]
@aferreroc 

Please visit the runbot page and and login with creadentials admin admin

http://runbot.odoo-community.org/runbot/128/8.0

then go to Management System -> Audits and click on the Quality Audiot.
There in the Verification List tab you will find 3 verification lists of which 2 are Associated to Procedures.

![2017-06-11_05-55-55](https://user-images.githubusercontent.com/8398291/27008192-56001efc-4e6b-11e7-85b1-a2527564ef93.png)

Please let me know if this solves your problem?
