### ISSUE TITLE
Possibility to define an immediate action before the complete analysis of the causes and the problems behind the non-conformity

### ISSUE THREAD

**Issue by gva-acsone** [OCA/management-system#187]
Hello,

For one of our customers, I am actually analyzing the possibility of defining an immediate action to immediately 'solve' the problem related to my non-conformity before proceeding to the whole analysis of the causes and triggers of my non-conformity.

According to me, this makes sense as in certain cases and industries (pharmaceutical industry for instance), as soon you notice the non-conformity, you have to take an immediate action to counter the problem, without having the time to start analyzing all the reasons and causes that have led to the problem. This process of analyzing comes afterwards, in order to prevent similar problems from happening in the future. Corrective, preventive and improvement opportunities will result from this analysis. 

If we take the example of a particular pharmaceutical product (example evoked by our customer) that has to be stored at a certain temperature in order to be used properly, as soon as the company notices that the product hasn't been stored at the right temperature, they have to immediately get rid of it by following certain procedures. They take an immediate action. Afterwards, when the problem has been solved and the danger avoided , they can start the analysis and discover how it comes that that particular article wasn't stored properly. 

I understand that in most cases, an analysis is necessary and useful to understand what to do as an immediate action, but I believe that it would be interesting to also allow users to insert an immediate action before the analysis state. As the analysis field is mandatory, this is actually impossible. 

I would be interested to have your feedback on this issue. Thanks!

**Comment by max3903** [comment]
@gva-acsone I have no problem moving the immediate action field on the analysis tab, if that's what you are asking for.

**Comment by gva-acsone** [comment]
My idea was either to add: 

- A new tab that is already visible at the draft 'stage'. That's what our customer prefers. This tab would only contain the 'immediate action' field, that I would then remove from the 'causes and analysis' tab (invisible at the 'draft' stage). As the NC is still in draft mode, I don't really fancy this option as actions will already been taken while the NC is not confirmed.
- A new 'Immediate Action' stage between the 'draft' and the 'analysis' stage. The tab I describe in the first option would then appear at that moment. If no immediate action has to be taken, users can skip this stage and immediately move on to the 'causes and analysis' stage.
- A 'Create an immediate action' button that would allow users to create an immediate action directly from the 'draft' stage.

**Comment by max3903** [comment]
@gva-acsone What about moving the immediate action field to the "Description" tab?

**Comment by gva-acsone** [comment]
@max3903  Works for me too!

**Comment by max3903** [comment]
@gva-acsone Let's do that then. Thanks!
