### ISSUE TITLE
Nonconformities shifted to the right said

### ISSUE THREAD

**Issue by MakMas** [OCA/management-system#195]
Hello,

I have problem with module Nonconformities. 
When I create new Nonconformities and write Description witch has more than 200 symbols than save, all  my Nonconformities shifted to the right said

![2017-07-12_13h06_39](https://user-images.githubusercontent.com/24442649/28114853-e6151cae-6702-11e7-96d5-6ec49ee850a4.png)

**Comment by eugen-don** [comment]
thanks ill fix that asap

**Comment by dreispt** [comment]
v10?

**Comment by MakMas** [comment]
Yes

**Comment by dreispt** [comment]
Just tried on [Runbot](https://runbot.odoo-community.org/runbot/repo/github-com-oca-management-system-128) (using both Firefox and Edge) and everything looks good:

![2017-08-11 14_56_18-mail - inbox - ibm notes](https://user-images.githubusercontent.com/1246629/29216121-72bcc5f8-7ea5-11e7-9954-fbfdcc31c737.png)

**Comment by MakMas** [comment]
Hello,

It's still not work correctly, please make Nonconformities for example with 200 letters. I logged to Runbot and create: nonconfomities "TEXT-size" please look it.
![2018-04-12_16h55_59](https://user-images.githubusercontent.com/24442649/38685962-828cbe82-3e73-11e8-8d7b-59f82b731ed0.png)

**Comment by max3903** [comment]
@MakMas Thanks for following up and sorry for the late reply. Please review the fix in #212.

**Comment by MakMas** [comment]
Thanks, now everything works fine

**Comment by max3903** [comment]
@MakMas Can you leave your review on the pull request:
https://github.com/OCA/management-system/pull/212/files

![screenshot from 2018-04-13 08-05-40](https://user-images.githubusercontent.com/939952/38736409-caa85d26-3ee0-11e8-85ac-a8efd9127ecc.png)
