### ISSUE TITLE
How to install QMS on Synology NAS?

### ISSUE THREAD

**Issue by MasterT2008** [OCA/management-system#196]
I just installed Odoo 8 on my Synology nas, but the QMS part is not included.
I downloaded the Zip file for v 8.0.1.0.0 and copied to my nas.
Then I moved it into :/volume1/@appstore/Odoo8/addons
On first attempt, none of it was found in the module section.
After a complete reset of my nas, clean install of Odoo 8, Odoo will not start after moving the files and folders.

Any suggestions?

**Comment by max3903** [comment]
Hello @MasterT2008 

Do you have all the dependencies in the zip file?
After moving the files, did you restart Odoo and update the list of modules?
Can you check the log and determine why Odoo is not starting?

**Comment by MasterT2008** [comment]
Hello @max3903 

It was after the first installation I discovered about the dependencies. 
knowledge
server-tools
web
Right?
But then each of these had their own dependencies which was not on the NAS and a my IT engineer helped me to look into this, but in the end, I bricked our Synology NAS and had to do a factory reset.
My IT engineer suggested to install Odoo 10 which is not currently available on the NAS so I do not know how to do that and I also doubt it would help in this case.

Of course I did a reinstall of Odoo before I got the reply from you, but is was something about the IP address showing 0.0.0.0:8069 and a lot of messages with the German word for tools. Werkzeuge.

Getting Odoo with the QMS is essensial for our business. 
Would it be easier to install it on a clean Linux computer instead of a Synology NAS even a NAS is preferable?

Thanx!

**Comment by MasterT2008** [comment]
Just to give it a try, I've successfully installed Odoo 10 on Windows 10 instead. 
Just wonder where to place the QMS files. 
Are there still dependencies?

**Comment by max3903** [comment]
@MasterT2008 

If "Getting Odoo with the QMS is essensial for [y]our business.", a NAS is not the right solution. A server with resources matching your usage with Ubuntu would be my recommendation.

Yes, there are still dependencies.

**Comment by MasterT2008** [comment]
Hi Max, 

I got a go to purchase a new server for testing Odoo instead :)
QMS modules now installs, however when I check any of the settings, I always get directed to the app store?

What am I doing wrong?

Thank you!

![screen1](https://user-images.githubusercontent.com/30310599/28510697-17e206ac-704a-11e7-8dc6-84bd4c6b33c7.jpg)
![screen2](https://user-images.githubusercontent.com/30310599/28510701-1ace1e32-704a-11e7-9804-9e0e392705cb.jpg)

**Comment by max3903** [comment]
@MasterT2008 

Not all the modules have been migrated to version 10. You can check the status here: #159

**Comment by MasterT2008** [comment]
@max3903 
Thank you. I've managed to install Odoo 8 on a Win 10 computer and test it from there.
Also for some reason, I have to install most of the packages I need on the Synology NAS before I even try to add extra modules or else I get tons of php error messages.

I will take it further with our IT guy.
