### ISSUE TITLE
It should be 'web.base.url' (in our systems the url link in the action email always points to localhost:8069

### ISSUE THREAD

**Issue by fdvarela** [OCA/management-system#202]
https://github.com/OCA/management-system/blob/a4f747ff21abf092b776d6602543e06d40b198ba/mgmtsystem_action/mgmtsystem_action.py#L97

**Comment by max3903** [comment]
Hello @fdvarela 

Can you provide your version of Odoo please?

Thanks!

**Comment by fdvarela** [comment]
Version 8

**Comment by fdvarela** [comment]
Also the URL generated is weird. 
To workaround the issue I created web.base_url (with underscore) in the configuration and set it to our URL.
Now the URL in the email (the link to the action) is (HTML extract)

< a href = "https://erp.monteloeder.com/%5Bu'https://erp.monteloeder.com?db=monteloeder#model=mgmtsystem.action&amp;id=1'%5D" style="font-weight: bold;">.....< / a >

It seems the <a href tag is prepended with the web.base_url and it is concatenated with the full (correct) url
