### ISSUE TITLE
[9.0^][mgmtsystem] Enterprise-like icon

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/management-system#204]
I've made a few enterprise-like icons for this module.

Which one do you prefer?

**Please comment any suggestions regarding icon and/or color.**

1:
![icon_03](https://user-images.githubusercontent.com/1914185/34918529-9c222cb4-f932-11e7-8321-f2cd77f60323.png)

2:
![icon_04](https://user-images.githubusercontent.com/1914185/34918531-9ebd6bd2-f932-11e7-9355-4d66348aff23.png)

3:
![icon_03](https://user-images.githubusercontent.com/1914185/34918635-9297974a-f934-11e7-86f5-3bcdd5899806.png)

4: (as suggested by @max3903 )
![knowledge_05](https://user-images.githubusercontent.com/1914185/34918852-b3898b1c-f938-11e7-845d-bb58e1b14740.png)

**Comment by max3903** [comment]
@ivantodorovich 1

What about modifying the module icon to make it "enterprise-like"? The one with the 3 arrows in circle.

**Comment by ivantodorovich** [comment]
Added item 4. 
3 arrows in circle, as suggested by @max3903

**Comment by max3903** [comment]
:+1: Number 4 then :)

**Comment by ivantodorovich** [comment]
@max3903 what do you think about adding a ✔️ inside of the circle? It's very common on quality managment system icons.

5:
![mgmt_03](https://user-images.githubusercontent.com/1914185/34952083-356b8004-f9f7-11e7-8bd3-b3a9c24c96b8.png)

**Comment by max3903** [comment]
@ivantodorovich Let's go with this one.
