### ISSUE TITLE
[10.0] Unable to modify Action Stages

### ISSUE THREAD

**Issue by remz1337** [OCA/management-system#208]
Even with all the access rights, my user account is unable to modify the Action stage.
Only the admin account can, so I believe the security settings are tied to the admin group.

**Comment by ivantodorovich** [comment]
https://github.com/OCA/management-system/pull/236 (https://github.com/OCA/management-system/pull/236/commits/16dc5eabac8f8487be510e0748bceea7b659b1bf) should fix it for `11.0`
