### ISSUE TITLE
How to install when not all modules are at the same Odoo version level ?

### ISSUE THREAD

**Issue by kgoderis** [OCA/management-system#223]
[This issue is not related to the code base itself, but I found no better place to post this]
[And I am by no means an python developer nor familiar with Odoo internals]

On https://www.odoo.com/apps/modules/browse?search=mgmtsystem the list of various ISO-modules indicate different Odoo versions being supported. I have a v10 test instance on which I would like to install the ISO 9K, 14K and 18K modules. I started by installing the mgmtsystem_quality package first (v10 rated), but mgmtsystem_health_safety and mgmtsystem_environment  are rated v8. 

How to proceed without breaking the base packages?

When trying to configure the settings of mgmtsystem_quality and enabling the other Systems, the user gets redirected to the odoo App Store home page. IMHO, it would be more clear to redirect to the specific link of the selected System

**Comment by max3903** [comment]
@kgoderis The v8 modules needs to be migrated to v10. Installing them as is on v10 will certainly fail.

You can look at #92 and #159 to know the state of the migration. 

If you want to finance the migration of the remaining modules, please send a mail to contact@opensourceintegrators.com or contact any contributor of your choice (cf module description).
