### ISSUE TITLE
[Quality][v10] Unable to edit Action -> Stages

### ISSUE THREAD

**Issue by kgoderis** [OCA/management-system#225]
In the Configuration settings of the Management System app editing of Action -> Stages is not enabled/impossible. Nonconformities -> Stages however can be edited/modified

[This happens with a user that has full authorisations in its profile]

**Comment by ivantodorovich** [comment]
https://github.com/OCA/management-system/pull/236 (https://github.com/OCA/management-system/pull/236/commits/16dc5eabac8f8487be510e0748bceea7b659b1bf) should fix it for `11.0`
