### ISSUE TITLE
res.config.setting.issue

### ISSUE THREAD

**Issue by RishabhJadia** [OCA/management-system#261]
Unable to save the settings in this module. Whenever I am clicking on  any type of settings for management systems configuration, it is not getting saved.

![image](https://user-images.githubusercontent.com/26570284/64167887-f7736900-ce67-11e9-95db-db52730b633f.png)

**Comment by max3903** [comment]
Hello @RishabhJadia 

Can you provide the version of Odoo you are using?

**Comment by RishabhJadia** [comment]
Hello @max3903 
Right Now I am running in runbot but want to migrate it to odoo12.

**Comment by max3903** [comment]
@RishabhJadia Some of the modules you selected have not been migrated to version 12 yet. That's why you get the current behavior.

If you have funding available, please contact@opensourceintegrators.com with the list of modules you need. Thank you.

**Comment by RishabhJadia** [comment]
@max3903 
But I am facing the same issue in odoo 10 runbot.

**Comment by Tempronics1** [comment]
I installed this module in Odoo V12 and I'm having the same issue of saving my settings. Is there any idea when all the features will be migrated?

**Comment by max3903** [comment]
@Tempronics1 You can check the status on this issue #234. If you have budget to speed up the migration, I suggest you contact a local OCA integrator https://odoo-community.org/integrators
