### ISSUE TITLE
ISO 9001:2015 

### ISSUE THREAD

**Issue by gokhandeveloper** [OCA/management-system#363]
Does this comply with ISO 9001:2015?
Also does the document management system have the ability to use custom sequence in documents?
For example, 
AAA FILE PATH> AAA 101 - FILE.docx
AAA FILE PATH> AAA 102 - FILE2.docx
?

**Comment by vincentlaurent** [comment]
I would say that it is perfect for the management of CAPA, complaints,... Regarding document management, I suggest to use more specialized solutions
