### ISSUE TITLE
[13.0] error in setup command: mgmtsystem\odoo\addons must contain exactly one installable Odoo addon dir, found []

### ISSUE THREAD

**Issue by Daud-stack** [OCA/management-system#502]
## Module
setup.py.

## Describe the bug
:\Users\d\Desktop\management-system-13.0\venv\Scripts\python.exe C:/Users/d/Desktop/management-system-13.0/setup/mgmtsystem/setup.py
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
error in setup command: C:\Users\d\Desktop\management-system-13.0\setup\mgmtsystem\odoo\addons must contain exactly one installable Odoo addon dir, found []

Process finished with exit code 1

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by max3903** [comment]
@sbidoul I am not sure what's going wrong with packaging here. Can you review and provide guidance?

**Comment by sbidoul** [comment]
`setup/mgmtsystem/odoo/addons/mgmtsystem` must be a symbolic link. These tend to be lost by contributors working on windows.

**Comment by max3903** [comment]
It is a symbolic link:
https://github.com/OCA/management-system/tree/13.0/setup/mgmtsystem/odoo/addons

**Comment by sbidoul** [comment]
@Daud-stack we don't really support this on windows. It may work, but few have tried. At least you need to make sure symbolic links are supported by your Windows setup, which is often not the default configuration.
