### ISSUE TITLE
Bug oca_dependencies.txt v15

### ISSUE THREAD

**Issue by NoemieUylenbroeck** [OCA/management-system#506]
Cannot checkout on the 15.0 branch on Windows because the first character of the name is a blank space.

## Module
N/A

## Describe the bug
error: invalid path

## To Reproduce
15.0

1. Use git on windows
2. checkout 15.0 
3.

**Expected behavior**
N/A

**Additional context**
windows

**Comment by max3903** [comment]
@NoemieUylenbroeck Thank you for reporting the issue. Can you try again and close this issue if it works?
