### ISSUE TITLE
Documentation menu missing 

### ISSUE THREAD

**Issue by me-Lee** [OCA/management-system#527]
I have installed management system into my Odoo Enterprise v16 (which is hosted on soladrive.com) and there is no 'Documentation' menu visible. I have tried uninstalling & reinstalling but get the same problem.

Screenshot here: https://aviamax.tinytake.com/msc/ODQ3MzE2Nl8yMTc4MzYzNw

**Comment by max3903** [comment]
@me-Lee Can you check if your user is in the "Management System / Viewer" group? (Settings > Users & Companies > Users)

**Comment by me-Lee** [comment]
Yes, I have all options ticked. See image: https://aviamax.tinytake.com/msc/ODQ3NDY0Nl8yMTc4NTYxNQ

**Comment by max3903** [comment]
@me-Lee Can you provide a screenshot of the "Manuals" menu item in Settings > Technical > User Interface > Menu Items?

It should look like this:
![Screenshot from 2023-07-21 07-51-45](https://github.com/OCA/management-system/assets/939952/468fb4b0-72b8-4c00-92b3-75064f516d3f)

**Comment by me-Lee** [comment]
Hi, here is the image: https://aviamax.tinytake.com/msc/ODQ3NzI3M18yMTc4ODY1Ng

**Comment by max3903** [comment]
@me-Lee Everything looks good. Can you create a new database and install only the mgmtsystem_quality module?

**Comment by me-Lee** [comment]
Just created a new database with no modules installed apart from the management system and the missing menu item is now there :/

**Comment by max3903** [comment]
Try installing one module at a time to determine which one is creating that conflict.

**Comment by me-Lee** [comment]
I have installed all modules one at a time into the empty database and the management system is working correctly with all the menu items showing. I'm at a bit of a loss now.
