### ISSUE TITLE
Management System Claim Bug.

### ISSUE THREAD

**Issue by ko-eska** [OCA/management-system#532]
## Module
mgmtsystem_claim.

## Describe the bug
There is a bug in Claim Description and Follow Up page view of create new claim form.

## To Reproduce
**Affected versions**: 16.0

1. XML codes should be rewritten according to version 16.
2.
3.

**Expected behavior**
An organized page structure..

**Additional context**
I attached a screenshot from odoo.
![mngmt](https://github.com/OCA/management-system/assets/117066449/a430bb33-072b-48f4-9754-bc01e163b8f4)

**Comment by max3903** [comment]
@ko-eska Thanks for reporting. I will take a look at it when I can. No guarantee about the delay.

**Comment by ms-eska** [comment]
@max3903 
I figure out that just before notebook tag group tag created to fixed the grid from 12 to 4. Removing that group will solve the issue/bug.

`<form string="Claim">
                <header>
                    <field name="stage_id" widget="statusbar" options="{'clickable': 1}"/>
                </header>
                <sheet string="Claims">
                    <group>
                        <field name="reference"/>
                        <field name="company_id" groups="base.group_multi_company"/>
                        <field name="name"/>
                        <field name="date"/>
                        <field name="team_id" invisible="1"/>
                    </group>
                    <group colspan="4" col="4" groups="base.group_user">
                        <field name="user_id"/>
                        <field name="priority"/>
                        <field name="categ_id"/>
                        <field name="date_deadline"/>
                    </group>
                    ****
                        <notebook>`

**Comment by max3903** [comment]
@ms-eska Yes, this is included in the pull request:
https://github.com/OCA/management-system/pull/535/files#diff-163e891aa36b6d3d5c6da69c4ab3bf0f142f9bd78fd5d517af30cc0f9545f2d0L55
