### ISSUE TITLE
Help activating modules

### ISSUE THREAD

**Issue by Mvpblcruz** [OCA/management-system#567]
Hello,

On the Quality Management System - Odoo V12 - we are not able to activate all features. 
On "Aplications" we can not activate "Claims" or "Manage documents approval"
![imag1](https://github.com/OCA/management-system/assets/124779453/16ab1124-13bc-4182-9375-0849725823d5)

On the section "Manuals" we can only activate "Quality manual Template", and we can not ativate the other options 3 options.

Can you please help us.

Thanks in advanced

**Comment by pedrobaeza** [comment]
They correspond to non ported modules.

**Comment by Mvpblcruz** [comment]
Sorry I did not understand.
Can you tell me what you mean by non ported modules? Is because of the Odoo version v12? Does it work on Oddo v15 or 17?

**Comment by pedrobaeza** [comment]
They are not migrated.
