### ISSUE TITLE
[17-0][FIX] wrong file presence: pandoc-3.1.9-1-amd64.deb

### ISSUE THREAD

**Issue by mymage** [OCA/management-system#585]
Hi, starting looking on 17.0 for translation, I found the 30MB **pandoc-3.1.9-1-amd64.deb** file on the repository root.
I suppose this is an error.

**Comment by mymage** [comment]
@max3903 Hi Maxime, I saw you are active in this repo. Do you think I have to do a PR to better fix this problem?

**Comment by max3903** [comment]
@mymage yes please

**Comment by pedrobaeza** [comment]
But removing it through an extra PR only provokes 60 MB of diff download (30 MB of addition and 30 MB of removal). The branch should be rewritten avoiding at all this file.

**Comment by mymage** [comment]
@pedrobaeza Your suggestion is out of my knowledge. I think that is a job for someone with "superpower" like a @OCA/management-systems-maintainers. If one kind person will take care of this, I ask him to post here a message. In the mean time I'll stress my skilled friends to try to propose a solution.

**Comment by pedrobaeza** [comment]
Yes, that's something to be done by @max3903 for example.

**Comment by max3903** [comment]
Fixed!

**Comment by mymage** [comment]
@max3903 Great! 
A dummy question: to recover the merged PR the single "pusher" had to re-push* (in this case I will ping them) or there is another way?
\* Not right away because they have the dirty file inside. Before they have to do a rebase, right?

**Comment by pedrobaeza** [comment]
```
git fetch origin 17.0
git reset --hard origin/17.0
```
or
```
git rebase origin/17.0
```
for other branches

**Comment by mymage** [comment]
@pedrobaeza Thanks!
