### ISSUE TITLE
Host for quality_control_* modules

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/management-system#80]
Do you think we can host here this module: https://github.com/odoomrp/odoomrp-wip/tree/8.0/quality_control and related ones?

**Comment by max3903** [comment]
Ana and I discussed this at Odoo Experience and we decided to leave those module in OCA/manufacture:
https://github.com/odoomrp/odoomrp-wip/wiki/Migration-to-OCA

The integration will be done with crm.claim. There may be some overlapping with the current features of those modules. The idea is that crm.claim are the output of manufacture and the input of management systems. We agreed to work on the integration and solve the overlap of scope later in the summer.

If you are available, please go ahead and have a look at mgmtsystem_claim. If you have any question, @dreispt and I can certainly help you.

**Comment by pedrobaeza** [comment]
Checking the module _mgmtsystem_claim_, I see that it's only a bit of fields more over crm.claim object, so I see no problem to keep both models instead of making an effort to integrate questions and answers in claims. We already have a module that makes the integration between claims and failed inspections: https://github.com/odoomrp/odoomrp-wip/tree/8.0/quality_control_claim, with configuration for auto-creating or not the claims, so I think it's enough for covering all the needs and integrate our modules with the set of management system modules.

**Comment by dreispt** [comment]
I agree that product quality can be a use case quite different from management systems, so it makes sense for it to go along manufacturing modules.
